plot1 <- function(){
    # Using the base plotting system, make a plot showing the total PM2.5 emission 
    # from all sources for each of the years 1999, 2002, 2005, and 2008 
    
    # Question: Have total emissions from PM2.5 decreased in the United States from 1999 to 2008?
    
    
    # Load data from RDS files. The RDS data files must be located in the same
    # directory ar the script file plot1.
    data.emissions.PM2.5 <- readRDS("summarySCC_PM25.rds")

    #caclulate total Emissions by year and store in a new variable
    data.emissions.PM2.5.annual.total <- aggregate(data.emissions.PM2.5$Emissions, by = list(data.emissions.PM2.5$year), FUN = sum)
    
    #replace default names generated by "aggregate" with new meaningful names
    names(data.emissions.PM2.5.annual.total) <- c("year", "Emissions")
    
    #scale the emission values to "millions of tons"
    data.emissions.PM2.5.annual.total$Emissions <- data.emissions.PM2.5.annual.total$Emissions / 1000000
    
    #initiate PNG graphical device
    png("plot1.png")

    #setup an empty plot
    plot(data.emissions.PM2.5.annual.total,
         type = "n",
         main = "Total Annual Emissions",
         xlab = "Year",
         ylab = "Emissions (millions of tons)")
    
    #add total annual emission points
    points(data.emissions.PM2.5.annual.total, 
           pch = 19)
    
    #add regression line to show direction of emission change
    with(data.emissions.PM2.5.annual.total, abline(lm(Emissions ~ year)))
    
    #close PNG graphical device and save the PNG file
    dev.off()
}