plot2 <- function(){
    # Use the base plotting system to make a plot answering this question. 
    
    # Question: Have total emissions from PM2.5 decreased in the Baltimore City, Maryland (fips == "24510") from 1999 to 2008?
    
    
    # Load data from RDS files. The RDS data files must be located in the same
    # directory ar the script file plot1.
    data.emissions.PM2.5 <- readRDS("summarySCC_PM25.rds")
    
    #apply filter to include data for fips = "24510" and years (1999, and 2008)
    data.emissions.PM2.5 <- subset(data.emissions.PM2.5, year %in% c(1999, 2008) & fips == "24510")

    #caclulate total Emissions by year and store in a new variable
    data.emissions.PM2.5.annual.total <- aggregate(data.emissions.PM2.5$Emissions, by = list(data.emissions.PM2.5$year), FUN = sum)
    
    #replace default names generated by "aggregate" with new meaningful names
    names(data.emissions.PM2.5.annual.total) <- c("year", "Emissions")
    
    #scale the emission values to "thousands of tons"
    data.emissions.PM2.5.annual.total$Emissions <- data.emissions.PM2.5.annual.total$Emissions / 1000
    
    #initiate PNG graphical device
    png("plot2.png")

    #setup an empty plot
    plot(data.emissions.PM2.5.annual.total,
         type = "n",
         main = "Annual Emissions change in Baltimore City",
         sub = "(1999 and 2008)",
         xlab = "Year",
         ylab = "Emissions (thousands of tons)",
         yaxt="n",
         xaxt="n")

    #add total annual emission points
    points(data.emissions.PM2.5.annual.total, 
           pch = 19)
    
    #add regression line to show direction of emission change
    with(data.emissions.PM2.5.annual.total, abline(lm(Emissions ~ year)))
    
    axis(side = 1, at = range(data.emissions.PM2.5.annual.total$year))
    axis(side = 2, at = range(data.emissions.PM2.5.annual.total$Emission))
    
    #close PNG graphical device and save the PNG file
    dev.off()
}