plot4 <- function(){
    library(ggplot2)

    # Question: Across the United States, how have emissions from coal combustion-related sources changed from 1999–2008??
    
    
    # Load data from RDS files. The RDS data files must be located in the same
    # directory ar the script file plot1.
    data.emissions.PM2.5 <- readRDS("summarySCC_PM25.rds")
    data.classification <- readRDS("Source_Classification_Code.rds")
    
    #apply filter to include data for coal combustion-related sources
    data.classification <- subset(data.classification, grepl("Coal", Short.Name) & grepl("Comb", Short.Name))

    #apply filter to include data for coal combustion-related sources and years 1999 and 2008
    data.emissions.PM2.5 <- subset(data.emissions.PM2.5, SCC %in% data.classification$SCC & year %in% c(1999, 2008))

    #caclulate total Emissions by year and store in a new variable
    data.emissions.PM2.5.annual.total <- aggregate(data.emissions.PM2.5$Emissions, by = list(data.emissions.PM2.5$year), FUN = sum)
    
    #replace default names generated by "aggregate" with new meaningful names
    names(data.emissions.PM2.5.annual.total) <- c("year", "Emissions")

    #scale the emission values to "thousands of tons"
    data.emissions.PM2.5.annual.total$Emissions <- data.emissions.PM2.5.annual.total$Emissions / 1000

    #setup the plot
    qplot(year, 
          Emissions, 
          data = data.emissions.PM2.5.annual.total, 
          geom = "path", 
          xlab = "Year",
          ylab = "Emissions (thousands of tons)") +
    ggtitle(expression(atop("Annual Coal Emissions change in U.S", atop(italic("(1999, 2008)"), "")))) +
    scale_x_continuous(breaks = range(data.emissions.PM2.5.annual.total$year))

    ggsave(file="plot4.png")}