plot5 <- function(){
    library(ggplot2)

    # Question: How have emissions from motor vehicle sources changed from 1999–2008 in Baltimore City?
    
    
    # Load data from RDS files. The RDS data files must be located in the same
    # directory ar the script file plot1.
    data.emissions.PM2.5 <- readRDS("summarySCC_PM25.rds")
    data.classification <- readRDS("Source_Classification_Code.rds")

    #apply filter to include data for motor vehicle sources
    data.classification <- subset(data.classification, grepl("Vehicle", SCC.Level.Two))

    #apply filter to include data for motor vehicle sources for years 1999 and 2008 in Baltimore City
    data.emissions.PM2.5 <- subset(data.emissions.PM2.5, SCC %in% data.classification$SCC & year %in% c(1999, 2008) & fips == "24510")

    #caclulate total Emissions by year and store in a new variable
    data.emissions.PM2.5.annual.total <- aggregate(data.emissions.PM2.5$Emissions, by = list(data.emissions.PM2.5$year), FUN = sum)
    
    #replace default names generated by "aggregate" with new meaningful names
    names(data.emissions.PM2.5.annual.total) <- c("year", "Emissions")

    #setup the plot
    qplot(year, 
          Emissions, 
          data = data.emissions.PM2.5.annual.total, 
          geom = "path", 
          xlab = "Year",
          ylab = "Emissions") +
    ggtitle(expression(atop("Motor Vehicle Emissions change in Baltimore City", atop(italic("(1999, 2008)"), "")))) +
    scale_x_continuous(breaks = range(data.emissions.PM2.5.annual.total$year))

    ggsave(file="plot5.png")
}