plot6 <- function(){
    library(ggplot2)
    
    # Compare emissions from motor vehicle sources in Baltimore City with emissions from motor vehicle sources in 
    # Los Angeles County, California (fips == "06037")  
    
    # Question: Which city has seen greater changes over time in motor vehicle emissions?
    
    
    # Load data from RDS files. The RDS data files must be located in the same
    # directory ar the script file plot1.
    data.emissions.PM2.5 <- readRDS("summarySCC_PM25.rds")
    data.classification <- readRDS("Source_Classification_Code.rds")
    
    #apply filter to include data for motor vehicle sources
    data.classification <- subset(data.classification, grepl("Vehicle", SCC.Level.Two))
    
    #apply filter to include data for motor vehicle sources for years 1999 and 2008 in Baltimore City and LA
    data.emissions.PM2.5 <- subset(data.emissions.PM2.5, SCC %in% data.classification$SCC & year %in% c(1999, 2008) & fips %in% c("24510","06037"))
    
    #caclulate total Emissions by year and city and store in a new variable
    data.emissions.PM2.5.annual.total <- aggregate(data.emissions.PM2.5$Emissions, by = list(data.emissions.PM2.5$fips, data.emissions.PM2.5$year), FUN = sum)
    
    #replace default names generated by "aggregate" with new meaningful names
    names(data.emissions.PM2.5.annual.total) <- c("fips", "year", "Emissions")
    
    #add new "city" column
    data.emissions.PM2.5.annual.total$city <- ""
    
    #translate fips to city name
    data.emissions.PM2.5.annual.total[data.emissions.PM2.5.annual.total$fips == "24510", ]$city <- "Baltimore City"
    data.emissions.PM2.5.annual.total[data.emissions.PM2.5.annual.total$fips == "06037", ]$city <- "Los Angelos"
    
    #scale the emission values to "thousands of tons"
    data.emissions.PM2.5.annual.total$Emissions <- data.emissions.PM2.5.annual.total$Emissions / 1000

    #setup the plot
    qplot(year, 
          Emissions, 
          data = data.emissions.PM2.5.annual.total, 
          geom = "path", 
          color=city,
          xlab = "Year",
          ylab = "Emissions (thousands of tons)") +
    ggtitle(expression(atop("Motor Vehicle Emissions change in Baltimore City and LA", atop(italic("(1999, 2008)"), "")))) +
    scale_x_continuous(breaks = range(data.emissions.PM2.5.annual.total$year))

    ggsave(file="plot6.png")}